#pragma once

#include <regex>

#include "../Engine/Core/Core.h"
#include "../Engine/RHI/RHI.h"
#include "../Engine/Engine.h"
#include "../Engine/Launcher.h"
#include "../Engine/Renderer/Renderer.h"
#include "../Engine/UI/UIManager.h"
#include "../Engine/WindowData.h"
#include "../Engine/Scene/SceneManager.h"
#include "../Engine/UI/UIHelper.h"
#include "../Engine/Scene/SceneNode.h"
#include "../Engine/Scene/Scene.h"
#include "../Engine/AssetSystem/AssetSystem.h"
#include "../Engine/AssetSystem/AsyncUploader.h"
#include "../Engine/AssetSystem/AssetRegistry.h"
#include "../Engine/Project.h"
#include "../Engine/AssetSystem/TextureManager.h"
#include "../Engine/Scene/Component/Landscape.h"
#include "../Engine/Scene/Component/StaticMesh.h"
#include "../Engine/Scene/CameraInterface.h"
#include "../Engine/MeshTool/MeshToolCommon.h"
#include "../Engine/AssetSystem/MeshManager.h"
#include "../Engine/Renderer/DeferredRenderer/DeferredRenderer.h"
#include "../Engine/Scene/Component/PMXComponent.h"
#include "../Engine/Scene/Component/DirectionalLight.h"
#include "../Engine/Scene/Component/SpotLight.h"

#include "../Engine/Renderer/RenderSettingContext.h"